YNHM.WebApp/Controllers/HomePageController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using YNHM.Database;
using YNHM.Entities.Models;
using YNHM.Entities.TestResources;
using YNHM.RepositoryServices;
using YNHM.WebApp.Models;

namespace YNHM.WebApp.Controllers
{

    //TODO: VASSILIS Fix active tab on the navbar
    [Authorize]
    public class HomePageController : Controller
    {
        #region UserManager
        private ApplicationUserManager _userManager;

        public HomePageController()
        {
        }

        public HomePageController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        #endregion

        private readonly ApplicationDbContext dbContext = new ApplicationDbContext();
        private readonly RoomieRepository hsr = new RoomieRepository();

        // GET: HomePage
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult About()
        {
            return View();
        }

        public ActionResult People(string searchText, string selectOption)
        {
            Roomie currentRoomie = GetCurrentRoomie();

            if (currentRoomie.HasTest == false)
            {
                ViewBag.Message = "You have not yet taken the test. You have been redirected here instead.";
                return RedirectToAction("TestInfo", "Test");
            }

            List<Roomie> roomies = new List<Roomie>();
            try
            {
                roomies = dbContext.Roomies
                            .Where(r => r.Id != currentRoomie.Id && r.IsMatched == false && r.HasTest).ToList()
                            .Where(r => r.HasHouse != currentRoomie.HasHouse).ToList();

                if (!currentRoomie.HasHouse)
                {
                    var matchedWithRooms = dbContext.Roomies.Where(r => r.Id != currentRoomie.Id && r.IsMatched)
                        .Where(r => r.House.Roomies.Count != r.House.Bedrooms).ToList();
                    roomies.AddRange(matchedWithRooms);
                }
            }
            catch (Exception e)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, e.Message);
            }
            var compared = CompareRoomies(currentRoomie, roomies);

            #region Filtering

            if (!String.IsNullOrEmpty(searchText))
            {
                switch (selectOption)
                {
                    case "First Name": compared = compared.Where(x => x.Key.FirstName.ToUpper().Contains(searchText.ToUpper())).ToDictionary(x => x.Key, x => x.Value); break;
                    case "Percentage": compared = compared.Where(x => x.Value > Convert.ToInt32(searchText)).ToDictionary(x => x.Key, x => x.Value); break;
                }
            }


            #endregion

            PercentageVM vm = new PercentageVM()
            {
                CurrentUser = currentRoomie,
                Roomies = roomies,
                Compared = compared
            };

            return View(vm);
        }

        public ActionResult PersonalProfile(int? id, int? percentage)
        {
            if (id == null || percentage == null)
            {
                return View("Error");
            }
            var roomieId = id.GetValueOrDefault();
            Roomie roomie = null;
            try
            {
                roomie = hsr.GetById(roomieId);
            }
            catch (Exception e)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, e.Message);
            }
            if (roomie == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            var currentRoomie = GetCurrentRoomie();
            PersonalProfileVM vm = new PersonalProfileVM(currentRoomie, roomie, percentage.GetValueOrDefault());
            return View(vm);
        }

        public ActionResult Match(int matchedUserId)
        {
            Roomie currentRoomie = GetCurrentRoomie();
            Roomie match = dbContext.Roomies.Find(matchedUserId);

            var roomieWithHouse = currentRoomie.HasHouse == true ? currentRoomie : match;
            var roomieWithoutHouse = currentRoomie.HasHouse == false ? currentRoomie : match;

            bool roomsLeft = roomieWithHouse.House.Bedrooms - roomieWithHouse.House.Roomies.Count > 0 ? true : false;
            if (!roomsLeft)
            {
                TempData["message"] = "Sorry, you cannot add this person, your house is full. :(";
                return RedirectToAction("MatchDetails", "Manage");
            }

            Comparison compare = new Comparison();

            match.IsMatched = true;
            currentRoomie.IsMatched = true;

            dbContext.Entry(match).State = EntityState.Modified;
            dbContext.Entry(currentRoomie).State = EntityState.Modified;
            dbContext.SaveChanges();

            RoomiesPair pair = new RoomiesPair();
            pair.RoomieOneId = currentRoomie.Id;
            pair.RoomieTwoId = matchedUserId;
            pair.MatchPercentage = compare.CalculateMatchPercentage(currentRoomie.Test, match.Test);

            dbContext.Entry(pair).State = EntityState.Added;
            dbContext.SaveChanges();

            //Add roomie to House.Roomies & Add house to Roomie.House
            var house = roomieWithHouse.House;
            roomieWithoutHouse.HasHouse = true;
            dbContext.Entry(roomieWithoutHouse).State = EntityState.Modified;

            dbContext.Houses.Attach(house);
            dbContext.Entry(house).Collection("Roomies").Load();
            house.Roomies.Add(roomieWithoutHouse);
            dbContext.Entry(house).State = EntityState.Modified;
            dbContext.SaveChanges();

            TempData["message"] = "Great, you have been matched! Try to have some fun until you die! :D";
            return RedirectToAction("MatchDetails", "Manage");
        }

        public ActionResult House(int? houseId)
        {
            var house = dbContext.Houses.Find(houseId);
            return View(house);
        }

        [AllowAnonymous]
        public ActionResult Subscriptions()
        {
            var user = UserManager.FindById(User.Identity.GetUserId());
            return View(user);
        }

        [AllowAnonymous]
        public ActionResult AboutDevelopers()
        {
            return View();
        }

        //Helpers
        public Dictionary<Roomie, int> CompareRoomies(Roomie current, List<Roomie> others)
        {
            Comparison comp = new Comparison();
            Dictionary<Roomie, int> roomiesPercentages = new Dictionary<Roomie, int>();

            for (int i = 0; i < others.Count; i++)
            {
                int percent = comp.CalculateMatchPercentage(current.Test, others[i].Test);

                //Add to percentage if subscriber
                if (others[i].IsSubscribed)
                {
                    percent += 10;
                }
                roomiesPercentages.Add(others[i], percent);
            }
            return roomiesPercentages.OrderByDescending(r => r.Value).ToDictionary(x => x.Key, x => x.Value);
        }
        private Roomie GetCurrentRoomie()
        {
            string currentUserId = User.Identity.GetUserId();
            Roomie currentRoomie;

            var currentUser = UserManager.FindById(currentUserId);
            int currentRoomieId = currentUser.RoomieId;
            currentRoomie = dbContext.Roomies.Find(currentRoomieId);
            return currentRoomie;
        }

    }
}

YNHM.WebApp/Controllers/TestController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YNHM.Database;
using YNHM.Entities.Models;
using YNHM.Entities.TestResources;

namespace YNHM.WebApp.Controllers
{
    [Authorize]
    public class TestController : Controller
    {
        private readonly ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationUserManager userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                userManager = value;
            }
        }

        public TestController()
        {
        }
        public TestController(ApplicationUserManager applicationUserManager)
        {
            UserManager = applicationUserManager;
        }


        // GET: Test/TestInfo
        public ActionResult TestInfo()
        {
            var roomie = GetRoomie();
            return View(roomie);
        }

        //GET: Test/TakeTest
        public ActionResult TakeTest()
        {
            var roomie = GetRoomie();
            Test test = roomie.Test;

            if (roomie.Test == null)
            {
                RedirectToAction("NewTest", "Test");
            }

            ViewBag.Answers = new List<SelectListItem>()
            {
                new SelectListItem { Text = "Yes"},
                new SelectListItem { Text = "Maybe"},
                new SelectListItem { Text = "No"}
            };

            List<Question> Questions = new List<Question>()
            {
                //Housework
                new Question() { Text = "Does cleanliness matter in general?" },
                new Question() { Text = "Are you bothered by a sink full with plates?" },
                new Question() { Text = "Do you mind the house being dusty?" },
                new Question() { Text = "Is cleaning the toilet every day important to you?" },

                //Noise
                new Question() { Text = "Does noise matter in general?" },
                new Question() { Text = "Do you listen to music loud?" },
                new Question() { Text = "Do you value quiet in the house" },
                new Question() { Text = "Will you be with playing musical instruments?" },

                //Food
                new Question() { Text = "Is a vegan or vegetarian diet important to you?" },
                new Question() { Text = "Do you cook every day?" },
                new Question() { Text = "Is keeping your own groceries separate important?" },
                new Question() { Text = "Is eating with your housemates important?" },

                //Animals
                new Question() { Text = "Do you like animal companions?" },
                new Question() { Text = "Will you mind caring for the housemate's animal companions, if they are absent?" },

                //Friends
                new Question() { Text = "Doo you mind friends coming over?" },
                new Question() { Text = "Do you mind friends or significant others staying overnight?" },
                new Question() { Text = "Does hanging out with your housemates matter?" },

                //Smoking
                new Question() { Text = "Do you mind others smoking in the house?" },
                new Question() { Text = "Do you mind others smoking weed in the house?" }
            };
            return View(Questions);
        }

        //POST: Test/TakeTest
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult TakeTest(List<Question> questions)
        {
            var roomie = GetRoomie();
            var test = roomie.Test;

            if (ModelState.IsValid)
            {
                var testQuestions = test.Questions.ToList();

                for (int i = 0; i < testQuestions.Count; i++)
                {
                    testQuestions[i].Answer = questions[i].Answer;
                }

                roomie.HasTest = true;
                db.Entry(roomie).State = EntityState.Modified;
                db.Entry(test).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("TestDetails", "Test");
            }
            List<Question> Questions = test.Questions.ToList();

            return View(Questions);
        }

        //POST: Test/NewTest
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NewTest()
        {
            var roomie = GetRoomie();

            if (roomie.Test != null)
            {
                return RedirectToAction("TakeTest", "Test");
            }

            Test test = new Test()
            {
                Roomie = roomie,
                Name = $"{roomie.FirstName} {roomie.LastName}",
                Questions = new List<Question>()
                {
                    //Housework
                    new Question() { Text = "Does cleanliness matter in general?" },
                    new Question() { Text = "Are you bothered by a sink full with plates?" },
                    new Question() { Text = "Do you mind the house being dusty?" },
                    new Question() { Text = "Is cleaning the toilet every day important to you?" },

                    //Noise
                    new Question() { Text = "Does noise matter in general?" },
                    new Question() { Text = "Do you listen to music loud?" },
                    new Question() { Text = "Do you value quiet in the house" },
                    new Question() { Text = "Will you be with playing musical instruments?" },

                    //Food
                    new Question() { Text = "Is a vegan or vegetarian diet important to you?" },
                    new Question() { Text = "Do you cook every day?" },
                    new Question() { Text = "Is keeping your own groceries separate important?" },
                    new Question() { Text = "Is eating with your housemates important?" },

                    //Animals
                    new Question() { Text = "Do you like animal companions?" },
                    new Question() { Text = "Will you mind caring for the housemate's animal companions, if they are absent?" },

                    //Friends
                    new Question() { Text = "Do you mind friends coming over?" },
                    new Question() { Text = "Do you mind friends or significant others staying overnight?" },
                    new Question() { Text = "Does hanging out with your housemates matter?" },

                    //Smoking
                    new Question() { Text = "Do you mind others smoking in the house?" },
                    new Question() { Text = "Do you mind others smoking weed in the house?" }
                }
            };

            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index", "Test");
            }

            roomie.Test = test;
            db.Entry(roomie).State = EntityState.Modified;
            db.Tests.Add(test);
            db.SaveChanges();
            return RedirectToAction("TakeTest", "Test");
        }


        public ActionResult TestDetails()
        {
            var roomie = GetRoomie();
            var test = roomie.Test;
            return View(test);
        }

        //Helpers
        //TODO: VASSILIS: Move to Repo
        private Roomie GetRoomie()
        {
            var userId = User.Identity.GetUserId();
            var user = UserManager.FindById(userId);
            return db.Roomies.Find(user.RoomieId);
        }

    }
}

YNHM.WebApp/Views/Test/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Update/_LayoutL.cshtml";
}

<!-- ====================================
———	How It Works
===================================== -->
<section class="py-7 py-md-10">
    <div class="container">
        <div class="row pb-6 pb-md-9">
            <div class="col-sm-4 col-xs-12 order-md-1">
                <div class="text-center text-md-right my-5 my-md-0">
                    <img class="" data-src="~/Templates/Listty/StaticHTML/assets/img/works/works-big-1.png" src="~/Templates/Listty/StaticHTML/assets/img/works/works-big-1.png" alt="Image Works">
                </div>
            </div>
            <div class="col-sm-8 col-xs-12">
                <div>
                    <span class="mb-2 d-inline-block">Introduction</span>
                    <h2 class="h4 mb-4">To continue, take the test!</h2>
                    <p>Our website includes an extensive testing and matching mechanism to assure that you are paired with the most compatible people.</p>
                </div>
            </div>
        </div>

        <hr class="my-5">

        <div class="row py-5 py-md-9">
            <div class="col-sm-4 col-xs-12">
                <div class="text-center text-md-left mb-5 mb-md-0">
                    <img class="" data-src="~/Templates/Listty/StaticHTML/assets/img/works/works-big-2.png" src="~/Templates/Listty/StaticHTML/assets/img/works/works-big-2.png" alt="Image Works">
                </div>
            </div>
            <div class="col-sm-8 col-xs-12">
                <div class="text-left text-md-right">
                    <span class="mb-2 d-inline-block">Part 1</span>
                    <h2 class="h4 mb-4">Cleanliness</h2>
                    <p>You will find questions that concern the cleanliness of your new house and how you rotate the chores.</p>
                </div>
            </div>
        </div>

        <hr class="my-5">

        <div class="row pt-5 pt-md-9">
            <div class="col-sm-4 col-xs-12 order-md-1">
                <div class="text-center text-md-right mb-5 mb-md-0">
                    <img class="" data-src="~/Templates/Listty/StaticHTML/assets/img/works/works-big-3.png" src="~/Templates/Listty/StaticHTML/assets/img/works/works-big-3.png" alt="Image Works">
                </div>
            </div>
            <div class="col-sm-8 col-xs-12">
                <div>
                    <span class="mb-2 d-inline-block">Part 2</span>
                    <h2 class="h4 mb-4">Noise</h2>
                    <p>This second part concerns your preferences about noise and music in the house.</p>
                </div>
            </div>
        </div>

        <hr class="my-5">

        <div class="row py-5 py-md-9">
            <div class="col-sm-4 col-xs-12">
                <div class="text-center text-md-left mb-5 mb-md-0">
                    <img class="" data-src="~/Templates/Listty/StaticHTML/assets/img/works/works-big-2.png" src="~/Templates/Listty/StaticHTML/assets/img/works/works-big-2.png" alt="Image Works">
                </div>
            </div>
            <div class="col-sm-8 col-xs-12">
                <div class="text-left text-md-right">
                    <span class="mb-2 d-inline-block">Part 3</span>
                    <h2 class="h4 mb-4">Cooking and Groceries</h2>
                    <p>Do you have a specific diet? Do you have any particular habits concerning dining?</p>
                </div>
            </div>
        </div>

        <hr class="my-5">

        <div class="row pt-5 pt-md-9">
            <div class="col-sm-4 col-xs-12 order-md-1">
                <div class="text-center text-md-right mb-5 mb-md-0">
                    <img class="" data-src="~/Templates/Listty/StaticHTML/assets/img/works/works-big-3.png" src="~/Templates/Listty/StaticHTML/assets/img/works/works-big-3.png" alt="Image Works">
                </div>
            </div>
            <div class="col-sm-8 col-xs-12">
                <div>
                    <span class="mb-2 d-inline-block">Part 4</span>
                    <h2 class="h4 mb-4">Animals</h2>
                    <p>If you prefer to live with humans only, declare so here. But, seriously, don't be a dick. Animals are cooler than humans.</p>
                </div>
            </div>
        </div>

        <hr class="my-5">

        <div class="row py-5 py-md-9">
            <div class="col-sm-4 col-xs-12">
                <div class="text-center text-md-left mb-5 mb-md-0">
                    <img class="" data-src="~/Templates/Listty/StaticHTML/assets/img/works/works-big-2.png" src="~/Templates/Listty/StaticHTML/assets/img/works/works-big-2.png" alt="Image Works">
                </div>
            </div>
            <div class="col-sm-8 col-xs-12">
                <div class="text-left text-md-right">
                    <span class="mb-2 d-inline-block">Part 5</span>
                    <h2 class="h4 mb-4">Smoking</h2>
                    <p>How do you feel about smoking in the house?</p>
                </div>
            </div>
        </div>

        <div class="py-7 py-md-0 bg-light">
            <div class="container position-relative px-md-0 d-flex justify-content-center">
                @using (Html.BeginForm("NewTest", "Test", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <button type="submit" class="btn btn-primary">Click here to continue!</button>
                }
            </div>
        </div>

    </div>
</section>

YNHM.WebApp/Views/Test/TakeTest.cshtml
@model List<YNHM.Entities.TestResources.Question>

@{
    ViewBag.Title = "TakeTest";
    Layout = "~/Views/Shared/Update/Dashboard/_LayoutDashboard.cshtml";
}

<section class="bg-light py-5 height100vh">
    <div class="container">
        @using (Html.BeginForm("TakeTest", "Test", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <h4>Cleanliness and Housework</h4>
            <div class="card">
                <div class="card-body px-6 pt-6 pb-1">
                    @Html.Label($"{Model[0].Text}")
                    @Html.DropDownList("[0].Answer", (IEnumerable<SelectListItem>)ViewBag.Answers, "Select an answer", new { @class = "select-default bg-white form-control",required = "required" })
                    @Html.ValidationMessage("[0].Answer")
                </div>
            </div>
            <div class="card">
                <div class="card-body px-6 pt-6 pb-1">
                    @Html.Label($"{Model[1].Text}")
                    @Html.DropDownList("[1].Answer", (IEnumerable<SelectListItem>)ViewBag.Answers, "Select an answer", new { @class = "select-default bg-white form-control", required = "required" })

                </div>
            </div>
            <div class="card">
                <div class="card-body px-6 pt-6 pb-1">
                    @Html.Label($"{Model[2].Text}")
                    @Html.DropDownList("[2].Answer", (IEnumerable<SelectListItem>)ViewBag.Answers, "Select an answer", new { @class = "select-default bg-white form-control", required = "required" })
                </div>
            </div>
            <div class="card">
                <div class="card-body px-6 pt-6 pb-1">
                    @Html.Label($"{Model[3].Text}")
                    @Html.DropDownList("[3].Answer", (IEnumerable<SelectListItem>)ViewBag.Answers, "Select an answer", new { @class = "select-default bg-white form-control", required = "required" })
                </div>
            </div>

            <h4>Noise</h4>
            <div class="card">
                <div class="card-body px-6 pt-6 pb-1">
                    @Html.Label($"{Model[4].Text}")
                    @Html.DropDownList("[4].Answer", (IEnumerable<SelectListItem>)ViewBag.Answers, "Select an answer", new { @class = "select-default bg-white form-control", required = "required" })
                </div>
            </div>
            <div class="card">
                <div class="card-body px-6 pt-6 pb-1">
                    @Html.Label($"{Model[5].Text}")
                    @Html.DropDownList("[5].Answer", (IEnumerable<SelectListItem>)ViewBag.Answers, "Select an answer", new { @class = "select-default bg-white form-control", required = "required" })
                </div>
            </div>
            <div class="card">
                <div class="card-body px-6 pt-6 pb-1">
                    @Html.Label($"{Model[6].Text}")
                    @Html.DropDownList("[6].Answer", (IEnumerable<SelectListItem>)ViewBag.Answers, "Select an answer", new { @class = "select-default bg-white form-control", required = "required" })
                </div>
            </div>
            <div class="card">
                <div class="card-body px-6 pt-6 pb-1">
                    @Html.Label($"{Model[7].Text}")
                    @Html.DropDownList("[7].Answer", (IEnumerable<SelectListItem>)ViewBag.Answers, "Select an answer", new { @class = "select-default bg-white form-control", required = "required" })
                </div>
            </div>
            <h4>Eating and Groceries</h4>
            <div class="card">
                <div class="card-body px-6 pt-6 pb-1">
                    @Html.Label($"{Model[8].Text}")
                    @Html.DropDownList("[8].Answer", (IEnumerable<SelectListItem>)ViewBag.Answers, "Select an answer", new { @class = "select-default bg-white form-control", required = "required" })
                </div>
            </div>
            <div class="card">
                <div class="card-body px-6 pt-6 pb-1">
                    @Html.Label($"{Model[9].Text}")
                    @Html.DropDownList("[9].Answer", (IEnumerable<SelectListItem>)ViewBag.Answers, "Select an answer", new { @class = "select-default bg-white form-control", required = "required" })
                </div>
            </div>
            <div class="card">
                <div class="card-body px-6 pt-6 pb-1">
                    @Html.Label($"{Model[10].Text}")
                    @Html.DropDownList("[10].Answer", (IEnumerable<SelectListItem>)ViewBag.Answers, "Select an answer", new { @class = "select-default bg-white form-control", required = "required" })
                </div>
            </div>
            <div class="card">
                <div class="card-body px-6 pt-6 pb-1">
                    @Html.Label($"{Model[11].Text}")
                    @Html.DropDownList("[11].Answer", (IEnumerable<SelectListItem>)ViewBag.Answers, "Select an answer", new { @class = "select-default bg-white form-control", required = "required" })
                </div>
            </div>
            <h4>Animals</h4>
            <div class="card">
                <div class="card-body px-6 pt-6 pb-1">
                    @Html.Label($"{Model[12].Text}")
                    @Html.DropDownList("[12].Answer", (IEnumerable<SelectListItem>)ViewBag.Answers, "Select an answer", new { @class = "select-default bg-white form-control", required = "required" })
                </div>
            </div>
            <div class="card">
                <div class="card-body px-6 pt-6 pb-1">
                    @Html.Label($"{Model[13].Text}")
                    @Html.DropDownList("[13].Answer", (IEnumerable<SelectListItem>)ViewBag.Answers, "Select an answer", new { @class = "select-default bg-white form-control", required = "required" })
                </div>
            </div>
            <h4>Guests</h4>
            <div class="card">
                <div class="card-body px-6 pt-6 pb-1">
                    @Html.Label($"{Model[14].Text}")
                    @Html.DropDownList("[14].Answer", (IEnumerable<SelectListItem>)ViewBag.Answers, "Select an answer", new { @class = "select-default bg-white form-control", required = "required" })
                </div>
            </div>
            <div class="card">
                <div class="card-body px-6 pt-6 pb-1">
                    @Html.Label($"{Model[15].Text}")
                    @Html.DropDownList("[15].Answer", (IEnumerable<SelectListItem>)ViewBag.Answers, "Select an answer", new { @class = "select-default bg-white form-control", required = "required" })
                </div>
            </div>
            <div class="card">
                <div class="card-body px-6 pt-6 pb-1">
                    @Html.Label($"{Model[16].Text}")
                    @Html.DropDownList("[16].Answer", (IEnumerable<SelectListItem>)ViewBag.Answers, "Select an answer", new { @class = "select-default bg-white form-control", required = "required" })
                </div>
            </div>
            <h4>Smoking</h4>
            <div class="card">
                <div class="card-body px-6 pt-6 pb-1">
                    @Html.Label($"{Model[17].Text}")
                    @Html.DropDownList("[17].Answer", (IEnumerable<SelectListItem>)ViewBag.Answers, "Select an answer", new { @class = "select-default bg-white form-control", required = "required" })
                </div>
            </div>
            <div class="card">
                <div class="card-body px-6 pt-6 pb-1">
                    @Html.Label($"{Model[18].Text}")
                    @Html.DropDownList("[18].Answer", (IEnumerable<SelectListItem>)ViewBag.Answers, "Select an answer", new { @class = "select-default bg-white form-control", required = "required" })
                </div>
            </div>

            <div class="row justify-content-center">
                <div class="col-md-7 col-lg-6 col-xl-5">
                    <div class="mb-6">
                        <button type="submit" value="TakeTest" class="btn btn-lg btn-primary btn-block">submit</button>
                    </div>
                </div>
            </div>
        }

    </div>
</section>

YNHM.WebApp/Views/Test/TestDetails.cshtml
@model YNHM.Entities.TestResources.Test
@{
    Layout = "~/Views/Shared/Update/Dashboard/_LayoutDashboard.cshtml";
}
@{ 
    int count = 1;
}

<section class="pb-8 pt-5 bg-light height100vh">
    <div class="container">
        <h2 class="font-weight-normal mb-4 mb-md-0">My Test Answers</h2>

        <table id="my-booking" class="display nowrap table-data-default" style="width:100%">
            <thead>
                <tr>
                    <th>Number</th>
                    <th>Question</th>
                    <th>Answer</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var q in Model.Questions)
                {
                    <tr>
                        <td>@count</td>
                        <td>@q.Text</td>
                        <td>@q.Answer</td>
                    </tr>
                    count++;
                }

            </tbody>
        </table>
        <div class="row justify-content-center" style="padding-top:10px !important">
            <div class="col-md-7 col-lg-6 col-xl-5">
                <div class="mb-6">
                    <a class="btn btn-lg btn-primary btn-block" href="@Url.Action("People","HomePage")">See your matches!</a>
                </div>
            </div>
        </div>
    </div>
</section>