YNHM.WebApp/Controllers/HomePageController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using YNHM.Database;
using YNHM.Entities.Models;
using YNHM.Entities.TestResources;
using YNHM.RepositoryServices;
using YNHM.WebApp.Models;

namespace YNHM.WebApp.Controllers
{

    //TODO: VASSILIS Fix active tab on the navbar
    [Authorize]
    public class HomePageController : Controller
    {
        #region UserManager
        private ApplicationUserManager _userManager;

        public HomePageController()
        {
        }

        public HomePageController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        #endregion

        private readonly ApplicationDbContext dbContext = new ApplicationDbContext();
        private readonly RoomieRepository hsr = new RoomieRepository();

        // GET: HomePage
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult About()
        {
            return View();
        }

        public ActionResult People(string searchText, string selectOption)
        {
            Roomie currentRoomie = GetCurrentRoomie();

            if (currentRoomie.HasTest == false)
            {
                ViewBag.Message = "You have not yet taken the test. You have been redirected here instead.";
                return RedirectToAction("TestInfo", "Test");
            }

            List<Roomie> roomies = new List<Roomie>();
            try
            {
                roomies = dbContext.Roomies
                            .Where(r => r.Id != currentRoomie.Id && r.IsMatched == false && r.HasTest).ToList()
                            .Where(r => r.HasHouse != currentRoomie.HasHouse).ToList();

                if (!currentRoomie.HasHouse)
                {
                    var matchedWithRooms = dbContext.Roomies.Where(r => r.Id != currentRoomie.Id && r.IsMatched)
                        .Where(r => r.House.Roomies.Count != r.House.Bedrooms).ToList();
                    roomies.AddRange(matchedWithRooms);
                }
            }
            catch (Exception e)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, e.Message);
            }
            var compared = CompareRoomies(currentRoomie, roomies);

            #region Filtering

            if (!String.IsNullOrEmpty(searchText))
            {
                switch (selectOption)
                {
                    case "First Name": compared = compared.Where(x => x.Key.FirstName.ToUpper().Contains(searchText.ToUpper())).ToDictionary(x => x.Key, x => x.Value); break;
                    case "Percentage": compared = compared.Where(x => x.Value > Convert.ToInt32(searchText)).ToDictionary(x => x.Key, x => x.Value); break;
                }
            }


            #endregion

            PercentageVM vm = new PercentageVM()
            {
                CurrentUser = currentRoomie,
                Roomies = roomies,
                Compared = compared
            };

            return View(vm);
        }

        public ActionResult PersonalProfile(int? id, int? percentage)
        {
            if (id == null || percentage == null)
            {
                return View("Error");
            }
            var roomieId = id.GetValueOrDefault();
            Roomie roomie = null;
            try
            {
                roomie = hsr.GetById(roomieId);
            }
            catch (Exception e)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, e.Message);
            }
            if (roomie == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            var currentRoomie = GetCurrentRoomie();
            PersonalProfileVM vm = new PersonalProfileVM(currentRoomie, roomie, percentage.GetValueOrDefault());
            return View(vm);
        }

        public ActionResult Match(int matchedUserId)
        {
            Roomie currentRoomie = GetCurrentRoomie();
            Roomie match = dbContext.Roomies.Find(matchedUserId);

            var roomieWithHouse = currentRoomie.HasHouse == true ? currentRoomie : match;
            var roomieWithoutHouse = currentRoomie.HasHouse == false ? currentRoomie : match;

            bool roomsLeft = roomieWithHouse.House.Bedrooms - roomieWithHouse.House.Roomies.Count > 0 ? true : false;
            if (!roomsLeft)
            {
                TempData["message"] = "Sorry, you cannot add this person, your house is full. :(";
                return RedirectToAction("MatchDetails", "Manage");
            }

            Comparison compare = new Comparison();

            match.IsMatched = true;
            currentRoomie.IsMatched = true;

            dbContext.Entry(match).State = EntityState.Modified;
            dbContext.Entry(currentRoomie).State = EntityState.Modified;
            dbContext.SaveChanges();

            RoomiesPair pair = new RoomiesPair();
            pair.RoomieOneId = currentRoomie.Id;
            pair.RoomieTwoId = matchedUserId;
            pair.MatchPercentage = compare.CalculateMatchPercentage(currentRoomie.Test, match.Test);

            dbContext.Entry(pair).State = EntityState.Added;
            dbContext.SaveChanges();

            //Add roomie to House.Roomies & Add house to Roomie.House
            var house = roomieWithHouse.House;
            roomieWithoutHouse.HasHouse = true;
            dbContext.Entry(roomieWithoutHouse).State = EntityState.Modified;

            dbContext.Houses.Attach(house);
            dbContext.Entry(house).Collection("Roomies").Load();
            house.Roomies.Add(roomieWithoutHouse);
            dbContext.Entry(house).State = EntityState.Modified;
            dbContext.SaveChanges();

            TempData["message"] = "Great, you have been matched! Try to have some fun until you die! :D";
            return RedirectToAction("MatchDetails", "Manage");
        }

        public ActionResult House(int? houseId)
        {
            var house = dbContext.Houses.Find(houseId);
            return View(house);
        }

        [AllowAnonymous]
        public ActionResult Subscriptions()
        {
            var user = UserManager.FindById(User.Identity.GetUserId());
            return View(user);
        }

        [AllowAnonymous]
        public ActionResult AboutDevelopers()
        {
            return View();
        }

        //Helpers
        public Dictionary<Roomie, int> CompareRoomies(Roomie current, List<Roomie> others)
        {
            Comparison comp = new Comparison();
            Dictionary<Roomie, int> roomiesPercentages = new Dictionary<Roomie, int>();

            for (int i = 0; i < others.Count; i++)
            {
                int percent = comp.CalculateMatchPercentage(current.Test, others[i].Test);

                //Add to percentage if subscriber
                if (others[i].IsSubscribed)
                {
                    percent += 10;
                }
                roomiesPercentages.Add(others[i], percent);
            }
            return roomiesPercentages.OrderByDescending(r => r.Value).ToDictionary(x => x.Key, x => x.Value);
        }
        private Roomie GetCurrentRoomie()
        {
            string currentUserId = User.Identity.GetUserId();
            Roomie currentRoomie;

            var currentUser = UserManager.FindById(currentUserId);
            int currentRoomieId = currentUser.RoomieId;
            currentRoomie = dbContext.Roomies.Find(currentRoomieId);
            return currentRoomie;
        }

    }
}

YNHM.WebApp/Controllers/PayPalController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using PayPal.Api;
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;
using YNHM.Database;

namespace YNHM.WebApp.Controllers
{
    [Authorize]
    public class PayPalController : Controller
    {
        private ApplicationUserManager _userManager;
        private ApplicationSignInManager _signInManager;
        public ApplicationSignInManager SignInManager
        {
            get { return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>(); }
            private set { _signInManager = value; }
        }
        public ApplicationUserManager UserManager
        {
            get { return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>(); }
            private set { _userManager = value; }
        }

        public PayPalController()
        {
        }

        public PayPalController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }


        public ActionResult PaymentWithPaypal(string Cancel = null)
        {
            //getting the apiContext  
            APIContext apiContext = PaypalConfiguration.GetAPIContext();

            try
            {
                //A resource representing a Payer that funds a payment Payment Method as paypal  
                //Payer Id will be returned when payment proceeds or click to pay  
                string payerId = Request.Params["PayerID"];
                if (string.IsNullOrEmpty(payerId))
                {
                    //this section will be executed first because PayerID doesn't exist  
                    //it is returned by the create function call of the payment class  
                    // Creating a payment  
                    // baseURL is the url on which paypal sendsback the data.  
                    string baseURI = Request.Url.Scheme + "://" + Request.Url.Authority + "/PayPal/PaymentWithPayPal?";
                    //here we are generating guid for storing the paymentID received in session  
                    //which will be used in the payment execution  
                    var guid = Convert.ToString((new Random()).Next(100000));
                    //CreatePayment function gives us the payment approval url  
                    //on which payer is redirected for paypal account payment  
                    var createdPayment = this.CreatePayment(apiContext, baseURI + "guid=" + guid);
                    //get links returned from paypal in response to Create function call  
                    var links = createdPayment.links.GetEnumerator();
                    string paypalRedirectUrl = null;
                    while (links.MoveNext())
                    {
                        Links lnk = links.Current;
                        if (lnk.rel.ToLower().Trim().Equals("approval_url"))
                        {
                            //saving the payapalredirect URL to which user will be redirected for payment  
                            paypalRedirectUrl = lnk.href;
                        }
                    }
                    // saving the paymentID in the key guid  
                    Session.Add(guid, createdPayment.id);
                    return Redirect(paypalRedirectUrl);
                }
                else
                {
                    // This function exectues after receving all parameters for the payment  
                    var guid = Request.Params["guid"];
                    var executedPayment = ExecutePayment(apiContext, payerId, Session[guid] as string);
                    //If executed payment failed then we will show payment failure message to user  
                    if (executedPayment.state.ToLower() != "approved")
                    {
                        return View("PaymentFailed");
                    }
                }
            }
            catch (Exception ex)
            {
                TempData["message"] = "We're sorry, something went wrong. Please try again later.";
                return RedirectToAction("Index", "HomePage");
            }

            var userId = User.Identity.GetUserId();
            var user = UserManager.FindById(userId);
            user.IsSubscribed = true;

            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                var roomie = db.Roomies.Find(user.RoomieId);
                roomie.IsSubscribed = true;
                db.Entry(roomie).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }

            if (user.SubscriptionStarts == null)
            {
                user.SubscriptionStarts = DateTime.Now;
            }

            if (user.SubscriptionExpires == null || user.SubscriptionExpires < DateTime.Now)
            {
                user.SubscriptionExpires = DateTime.Now.AddDays(30);
            }
            else
            {
                user.SubscriptionExpires = user.SubscriptionExpires.Value.AddDays(30);
            }

            var addRole = UserManager.AddToRole(user.Id, "Subscriber");
            if (addRole.Succeeded)
            {
                UserManager.Update(user);
            }


            TempData["message"] = "Your payment has been processed and has been accepted!";
            return RedirectToAction("Index", "HomePage");
        }
        private PayPal.Api.Payment payment;
        private Payment ExecutePayment(APIContext apiContext, string payerId, string paymentId)
        {
            var paymentExecution = new PaymentExecution()
            {
                payer_id = payerId
            };
            this.payment = new Payment()
            {
                id = paymentId
            };
            return this.payment.Execute(apiContext, paymentExecution);
        }
        private Payment CreatePayment(APIContext apiContext, string redirectUrl)
        {
            Item subscription = new Item()
            {
                name = "YNHM Subscription",
                currency = "EUR",
                price = "14",
                quantity = "1"
            };

            //create itemlist and add item objects to it  
            var itemList = new ItemList()
            {
                items = new List<Item>()
            };
            //Adding Item Details like name, currency, price etc  
            itemList.items.Add(subscription);

            var payer = new Payer()
            {
                payment_method = "paypal"
            };
            // Configure Redirect Urls here with RedirectUrls object  
            var redirUrls = new RedirectUrls()
            {
                cancel_url = redirectUrl + "&Cancel=true",
                return_url = redirectUrl
            };
            // Adding Tax, shipping and Subtotal details  
            var details = new Details()
            {
                tax = "1",
                subtotal = subscription.price
            };
            //Final amount with details  
            var amount = new Amount()
            {
                currency = "EUR",
                total = (Convert.ToInt32(details.tax) + Convert.ToInt32(subscription.price)).ToString(),
                details = details
            };
            var transactionList = new List<Transaction>();
            // Adding description about the transaction  
            transactionList.Add(new Transaction()
            {
                description = "Transaction description",
                invoice_number = Convert.ToString(new Random().Next(1000000)),
                amount = amount,
                item_list = itemList
            });
            this.payment = new Payment()
            {
                intent = "sale",
                payer = payer,
                transactions = transactionList,
                redirect_urls = redirUrls
            };
            // Create a payment using a APIContext  
            return this.payment.Create(apiContext);
        }



    }
}

YNHM.WebApp/Views/HomePage/About.cshtml
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/Update/Dashboard/_LayoutDashboard.cshtml";
}

<section class="py-7 py-md-10">
    <div class="container">
        <div class="row pb-6 pb-md-9">
            <div class="col-sm-4 col-xs-12 order-md-1">
                <div class="text-center text-md-right my-5 my-md-0">
                    <img class="" data-src="~/Templates/Listty/StaticHTML/assets/img/works/Register.png" src="~/Templates/Listty/StaticHTML/assets/img/works/Register.png" height="200" width="200" alt="Register">
                </div>
            </div>
            <div class="col-sm-8 col-xs-12">
                <div>
                    <span class="mb-2 d-inline-block">Step 1</span>
                    <h2 class="h4 mb-4">Register</h2>
                    <p>For privacy reasons, the full functionality of the website is not accessible to people that are not registered. So, the first step for you is to fill up the forms and join us!</p>
                </div>
            </div>
        </div>

        <hr class="my-5">

        <div class="row py-5 py-md-9">
            <div class="col-sm-4 col-xs-12">
                <div class="text-center text-md-left mb-5 mb-md-0">
                    <img class="" data-src="~/Templates/Listty/StaticHTML/assets/img/works/TakeTest.png" src="~/Templates/Listty/StaticHTML/assets/img/works/TakeTest.png" height="200" width="200"  alt="Image Works">
                </div>
            </div>
            <div class="col-sm-8 col-xs-12">
                <div class="text-left text-md-right">
                    <span class="mb-2 d-inline-block">Step 2</span>
                    <h2 class="h4 mb-4">Take the test</h2>
                    <p>This test will be used to match you with other users of the website. You can find out more before you take it, but the basic idea is to declare your preferences for a cohabitation.</p>
                </div>
            </div>
        </div>

        <hr class="my-5">

        <div class="row pt-5 pt-md-9">
            <div class="col-sm-4 col-xs-12 order-md-1">
                <div class="text-center text-md-right mb-5 mb-md-0">
                    <img class="" data-src="~/Templates/Listty/StaticHTML/assets/img/works/FindPerson.png" src="~/Templates/Listty/StaticHTML/assets/img/works/FindPerson.png" height="200" width="200"  alt="Image Works">
                </div>
            </div>
            <div class="col-sm-8 col-xs-12">
                <div>
                    <span class="mb-2 d-inline-block">Step 3</span>
                    <h2 class="h4 mb-4">Explore the results</h2>
                    <p>See your matches with other people, ranked by percentage. If you feel like it, you can see their profiles and decide if they are the right person for you to live with!</p>
                </div>
            </div>
        </div>
    </div>
</section>

YNHM.WebApp/Views/HomePage/AboutDevelopers.cshtml
@{
    Layout = "~/Views/Shared/Update/Dashboard/_LayoutDashboard.cshtml";
}


<section class="bg-light py-7 py-md-10">
    <div class="container align-content-center">
        <h2 class="text-align-center" style="padding-bottom:20px">Team DeathMatch for 2</h2>
    </div>
    <div class="container" style="display: flex !important; align-items: center !important; flex-wrap: wrap !important;">
        <div class="col-6" style="display: flex; flex-direction:column; align-items: center;">
            <div class="row">
                <div>
                    <img class="rounded rounded-md-left" data-src="~/Templates/Listty/StaticHTML/assets/img/developers/vassilis-linkedin-w350.jpg" src="~/Templates/Listty/StaticHTML/assets/img/developers/vassilis-linkedin-w350.jpg" alt="vassilis kotsmanidis profile photo jpg" />
                </div>
            </div>
            <div class="col-sm-8">
                <div class="p-6">
                    <h3 class="font-weight-normal mb-0">Vassilis Kotsmanidis</h3>
                    <span class="d-inline-block mb-5" style="font-size: 1rem; font-weight: 600"><i class="fa fa-code" aria-hidden="false"></i> Full Stack Web Developer </span>
                    <ul class="list-unstyled mb-5">
                        <li class="mb-2">
                            <i class="fa fa-phone-alt" aria-hidden="true"></i> +30 6945861652
                        </li>
                        <li class="mb-2">
                            <i class="fa fa-envelope" aria-hidden="true"></i> <a href="mailto:vassilis.kotsman@gmail.com"> vassilis.kotsman@gmail.com</a>
                        </li>
                        <li class="mb-2">
                            <i class="fab fa-linkedin-in" aria-hidden="true"></i> <a href="https://www.linkedin.com/in/vassilis-kotsmanidis/"> LinkedIn</a>
                        </li>
                        <li class="mb-2">
                            <i class="fab fa-github" aria-hidden="true"></i> <a href="https://github.com/KotsmanV"> Github</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-6" style="display: flex; flex-direction:column; align-items: center;">
            <div class="row">
                <div>
                    <img class="rounded rounded-md-left" data-src="~/Templates/Listty/StaticHTML/assets/img/developers/dimitra-linkedin-w350.jpg" src="~/Templates/Listty/StaticHTML/assets/img/developers/dimitra-linkedin-w350.jpg" alt="dimitra kamni profile photo jpg" />
                </div>
            </div>
            <div class="col-sm-8">
                <div class="p-6">
                    <h3 class="font-weight-normal mb-0">Dimitra Kamni</h3>
                    <span class="d-inline-block mb-5" style="font-size: 1rem; font-weight: 600"><i class="fa fa-code" aria-hidden="false"></i> Full Stack Web Developer </span>
                    <ul class="list-unstyled mb-5">
                        <li class="mb-2">
                            <i class="fa fa-phone-alt" aria-hidden="true"></i> +30 6978054547
                        </li>
                        <li class="mb-2">
                            <i class="fa fa-envelope" aria-hidden="true"></i> <a href="mailto:dimitra.kamni@gmail.com"> dimitra.kamni@gmail.com</a>
                        </li>
                        <li class="mb-2">
                            <i class="fab fa-linkedin-in" aria-hidden="true"></i> <a href="https://www.linkedin.com/in/dimitra-k/"> LinkedIn</a>
                        </li>
                        <li class="mb-2">
                            <i class="fab fa-github" aria-hidden="true"></i> <a href="https://github.com/DimitraK92"> Github</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

YNHM.WebApp/Views/HomePage/Subscriptions.cshtml
@using Microsoft.AspNet.Identity
@model YNHM.Entities.Models.ApplicationUser
@{
    ViewBag.Title = "Subscriptions";
    Layout = "~/Views/Shared/Update/Dashboard/_LayoutDashboard.cshtml";
}

@if (Model != null && Model.IsSubscribed)
{
    <section class="py-7 py-md-10">
        <div class="container">
            <div class="section-title">
                <h4>
                    Your Current Plan
                </h4>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-pricing border-primary">
                        <h2 class="card-title">
                            Premium
                        </h2>

                        <div class="pricing bg-primary">
                            <span class="price text-white">14</span>
                            <span class="year text-white">EUR/Month</span>
                        </div>
                        <div class="text-align-center">
                            <h5><strong>Expiration date:</strong> @Model.SubscriptionExpires.Value.ToString("d")</h5>
                        </div>
                        <div class="card-body px-7 px-md-3 px-lg-7">

                            <ul class="list-unstyled mt-4">
                                <li class="active mb-3">
                                    <i class="fa fa-check-square"></i>
                                    <span class="mb-0">Profile Customization</span>
                                </li>
                                <li class="active mb-3">
                                    <i class="fa fa-check-square"></i>
                                    <span class="mb-0">Test answers comparison</span>
                                </li>
                                <li class="active mb-3">
                                    <i class="fa fa-check-square"></i>
                                    <span class="mb-0">Appears higher in searches</span>
                                </li>
                                <li class="active mb-3">
                                    <i class="fa fa-check-square"></i>
                                    <span class="mb-0">Seaweed for silk ribbons</span>
                                </li>
                            </ul>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
}
else
{
    <section class="py-7 py-md-10">
        <div class="container">
            <div class="section-title">
                <h4>
                    Our website offers two packages with different user experience. Find out more below!
                </h4>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="card card-pricing">
                        <h2 class="card-title">
                            Free
                        </h2>

                        <div class="pricing">
                            <span class="price">0</span>
                            <span class="year">EUR/Month</span>
                        </div>

                        <div class="card-body px-7 px-md-3 px-lg-7">

                            <ul class="list-unstyled mt-4">
                                <li class="active mb-3">
                                    <i class="fa fa-check-square"></i>
                                    <span class="mb-0">Profile Customization</span>
                                </li>
                            </ul>
                        </div>

                        <div class="card-footer bg-transparent text-center border-top-0 pb-5 pt-4">
                            <a href="@Url.Action("Index","HomePage")" class="btn btn-outline-secondary">Get Started</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card card-pricing border-primary">
                        <h2 class="card-title">
                            Premium
                        </h2>

                        <div class="pricing bg-primary">
                            <span class="price text-white">14</span>
                            <span class="year text-white">EUR/Month</span>
                        </div>
                        <div class="card-body px-7 px-md-3 px-lg-7">

                            <ul class="list-unstyled mt-4">
                                <li class="active mb-3">
                                    <i class="fa fa-check-square"></i>
                                    <span class="mb-0">Profile Customization</span>
                                </li>
                                <li class="active mb-3">
                                    <i class="fa fa-check-square"></i>
                                    <span class="mb-0">Test answers comparison</span>
                                </li>
                                <li class="active mb-3">
                                    <i class="fa fa-check-square"></i>
                                    <span class="mb-0">Appears higher in searches</span>
                                </li>
                                <li class="active mb-3">
                                    <i class="fa fa-check-square"></i>
                                    <span class="mb-0">Seaweed for silk ribbons</span>
                                </li>
                            </ul>
                        </div>

                        <div class="card-footer bg-transparent text-center border-top-0 pb-5 pt-4">
                            <a href="@Url.Action("PaymentWithPaypal","PayPal")" class="btn btn-primary">Get Started</a>
                        </div>
                    </div>
                </div>
            </div>

            @{
                if (!User.Identity.IsAuthenticated)
                {
                    <div class="text-center pt-5">
                        <p class="mb-0 text-dark" style="font-size: 16px"> Don't have an Account? <a href="@Url.Action("Register","Account")">Sign up</a></p>
                    </div>
                }
            }
        </div>
    </section>
}